'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, EyeOff, KeyRound, LockKeyhole, ScanLine, ShieldCheck, TrendingUp } from 'lucide-react';

type DeskTab = 'TRADE' | 'SHIELD' | 'STEALTH' | 'COLLECT';
const TABS: { id: DeskTab; label: string; Icon: typeof ShieldCheck }[] = [
  { id: 'TRADE', label: 'Trade', Icon: TrendingUp },
  { id: 'SHIELD', label: 'Shield', Icon: ShieldCheck },
  { id: 'STEALTH', label: 'Send', Icon: EyeOff },
  { id: 'COLLECT', label: 'Keys', Icon: KeyRound },
];

export const PrivacyDeskSection: React.FC = () => {
  const [activeTab, setActiveTab] = useState<DeskTab>('SHIELD');
  const [leverage, setLeverage] = useState(25);

  return (
    <section id="desk" className="landing-panel landing-candy-coral flex min-h-[calc(100svh-2rem)] items-center justify-center px-5 py-32 sm:px-8 sm:py-40">
      <div className="pointer-events-none absolute -bottom-12 left-1/3 h-64 w-64 rounded-full bg-[#ffdf85]/35 blur-3xl" />

      <div className="relative z-10 flex w-full max-w-6xl flex-col items-center text-center">
        <div className="landing-sticker-label mb-8 border-white/45 bg-white/25 text-[#6e2b39]"><span className="h-2 w-2 rounded-full bg-[#ef315a]" /> PRIVACY DESK / INTERACTIVE PREVIEW</div>
        <h2 className="landing-scene-heading max-w-5xl text-[#641927]">PRIVATE MOVES,<br /><span className="text-[#fff4ed]">LIVE.</span></h2>
        <p className="landing-poster-copy mx-auto mt-9 max-w-2xl text-[#752f38]">One clean desk for shielded payments, private transfers, and the wallet boundary behind them.</p>

        <div className="mt-12 w-full max-w-4xl rounded-[2rem] border border-white/60 bg-white/30 p-2 shadow-[0_24px_60px_rgba(108,28,44,.18)] backdrop-blur-xl sm:p-3">
          <div className={`desk-card-shell desk-card-${activeTab.toLowerCase()} rounded-[1.55rem] border border-white/45 bg-[#1b101b]/95 p-4 text-left shadow-2xl sm:p-6`}>
            <div className="flex flex-wrap items-center justify-between gap-3 px-1 pb-4 font-mono text-[9px] uppercase tracking-[0.15em] text-[#c9a3a5]"><span className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400" /> ORRANGE / DESK</span><span className="flex items-center gap-2 text-[#ffb45c]"><ScanLine className="h-3 w-3" /> Testnet preview</span></div>
            <div className="rounded-[1.2rem] border border-white/10 bg-[#0e090d] p-4 sm:p-5">
              <div className="flex items-center justify-between gap-4 border-b border-white/10 pb-5"><div><div className="font-space text-xl font-semibold text-white">Privacy Desk</div><div className="mt-1 font-mono text-[9px] uppercase tracking-[0.15em] text-[#887078]">Make a move / choose a surface</div></div><div className="hidden rounded-full border border-emerald-400/25 bg-emerald-400/10 px-3 py-1.5 font-mono text-[9px] font-bold uppercase tracking-wider text-emerald-300 sm:block">Wallet connected</div></div>
              <div className="mt-5 grid grid-cols-4 gap-1 rounded-2xl border border-white/[0.08] bg-white/[0.025] p-1" role="tablist" aria-label="Privacy desk modes">{TABS.map(({ id, label, Icon }) => <button key={id} type="button" role="tab" aria-selected={activeTab === id} onClick={() => setActiveTab(id)} className={`flex items-center justify-center gap-1.5 rounded-xl px-2 py-2.5 font-mono text-[9px] font-bold uppercase tracking-wider transition-all sm:gap-2 sm:text-[10px] ${activeTab === id ? 'bg-[#fff6f0] text-[#26131e] shadow-lg' : 'text-[#9e8188] hover:bg-white/[0.06] hover:text-white'}`}><Icon className="h-3.5 w-3.5" />{label}</button>)}</div>
              <div key={activeTab} className={`desk-content-switch desk-card-${activeTab.toLowerCase()} mt-6 min-h-[17rem]`}>{activeTab === 'SHIELD' && <ShieldPanel />}{activeTab === 'STEALTH' && <SendPanel />}{activeTab === 'COLLECT' && <KeysPanel />}{activeTab === 'TRADE' && <TradePanel leverage={leverage} setLeverage={setLeverage} />}</div>
            </div>
            <div className="flex items-center justify-between px-1 pt-3 font-mono text-[9px] uppercase tracking-[0.13em] text-[#887078]"><span>Product preview / no fabricated balances</span><Link href="/wallet" className="text-[#ffb45c] hover:text-white">Open wallet →</Link></div>
          </div>
        </div>
        <div className="mt-7 flex w-full max-w-4xl justify-between px-2 font-mono text-[9px] uppercase tracking-[0.14em] text-[#88414c]"><span>03 / DESK</span><span>Click the modes</span></div>
      </div>
    </section>
  );
};

const DeskHeader: React.FC<{ Icon: typeof ShieldCheck; title: string; status: string }> = ({ Icon, title, status }) => <div className="flex items-center justify-between gap-4 border-b border-white/10 pb-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl border border-[#ffb45c]/30 bg-[#f97316]/15 text-[#ffb45c]"><Icon className="h-4 w-4" /></span><div><h3 className="font-space text-base font-semibold text-white">{title}</h3><div className="mt-1 font-mono text-[9px] uppercase tracking-[0.14em] text-[#887078]">STRK20 / wallet api</div></div></div><span className="rounded-full border border-[#ffb45c]/25 bg-[#f97316]/10 px-2 py-1 font-mono text-[9px] font-bold uppercase tracking-wider text-[#ffb45c]">{status}</span></div>;
const DeskMetric: React.FC<{ label: string; value: string; detail: string; accent?: boolean }> = ({ label, value, detail, accent }) => <div className={`rounded-2xl border p-4 ${accent ? 'border-[#ffb45c]/25 bg-[#f97316]/[0.08]' : 'border-white/10 bg-white/[0.025]'}`}><div className="font-mono text-[9px] uppercase tracking-[0.15em] text-[#887078]">{label}</div><div className={`mt-2 font-space text-sm font-semibold ${accent ? 'text-[#ffb45c]' : 'text-white'}`}>{value}</div><div className="mt-1 text-xs leading-5 text-[#aa8e95]">{detail}</div></div>;

const ShieldPanel: React.FC = () => <div className="animate-in fade-in duration-300"><DeskHeader Icon={ShieldCheck} title="Make funds private" status="Live flow" /><div className="mt-6 grid gap-3 sm:grid-cols-[1fr_auto_1fr] sm:items-center"><DeskMetric label="FROM" value="Public balance" detail="Your connected wallet" /><ArrowRight className="hidden h-4 w-4 text-[#ffb45c] sm:block" /><DeskMetric label="TO" value="Private note" detail="STRK20 privacy pool" accent /></div><div className="mt-5 flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.025] p-4"><LockKeyhole className="h-4 w-4 text-[#ffb45c]" /><p className="font-mono text-[10px] leading-5 text-[#aa8e95]">Your privacy wallet builds the note, generates the proof, and asks you to confirm.</p></div><Link href="/send?mode=deposit" className="landing-button mt-5 inline-flex w-full items-center justify-center gap-2 rounded-full bg-[#ffb45c] px-4 py-3 text-sm font-bold text-[#24111a] hover:bg-white">Make funds private <ArrowUpRight className="h-4 w-4" /></Link></div>;
const SendPanel: React.FC = () => <div className="animate-in fade-in duration-300"><DeskHeader Icon={EyeOff} title="Private transfer" status="Live flow" /><div className="mt-6 grid gap-3 sm:grid-cols-2"><DeskMetric label="RECIPIENT" value="Starknet address" detail="Registered for private receiving" /><DeskMetric label="PAYMENT" value="Shielded STRK20" detail="Amount and token stay inside the pool" accent /></div><div className="mt-5 rounded-2xl border border-emerald-400/20 bg-emerald-400/[0.06] p-4 font-mono text-[10px] leading-5 text-[#b5a2a4]">The live product flow is private send. Stealth links remain a future surface, clearly marked as such.</div><Link href="/send" className="landing-button mt-5 inline-flex w-full items-center justify-center gap-2 rounded-full bg-[#fff6f0] px-4 py-3 text-sm font-bold text-[#24111a] hover:bg-[#ffb45c]">Open private send <ArrowUpRight className="h-4 w-4" /></Link></div>;
const KeysPanel: React.FC = () => <div className="animate-in fade-in duration-300"><DeskHeader Icon={KeyRound} title="Wallet-owned privacy" status="Model" /><div className="mt-6 grid gap-3 sm:grid-cols-2"><DeskMetric label="VIEWING KEYS" value="Held by wallet" detail="The dapp never stores secrets" /><DeskMetric label="PROOFS" value="Generated on request" detail="Confirm in your privacy wallet" accent /></div><div className="mt-5 border-l border-[#ffb45c]/50 pl-4 font-mono text-[10px] leading-5 text-[#aa8e95]">Privacy works best when the boundary is visible: the wallet holds sensitive material, the dapp requests an action, and Starknet settles it.</div><Link href="/settings" className="landing-button mt-5 inline-flex items-center gap-2 rounded-full border border-[#ffb45c]/45 px-4 py-3 text-xs font-bold uppercase tracking-wider text-[#ffb45c] hover:bg-[#f97316]/10">Inspect controls <ArrowUpRight className="h-4 w-4" /></Link></div>;
const TradePanel: React.FC<{ leverage: number; setLeverage: (value: number) => void }> = ({ leverage, setLeverage }) => <div className="animate-in fade-in duration-300"><DeskHeader Icon={TrendingUp} title="Private trading surface" status="Coming next" /><div className="mt-6 rounded-2xl border border-white/10 bg-white/[0.025] p-4"><div className="flex items-end justify-between"><div><div className="font-mono text-[9px] uppercase tracking-wider text-[#887078]">Concept preview</div><div className="mt-2 font-space text-2xl font-semibold text-white">STRK / USD</div></div><span className="font-mono text-sm text-[#c4b5fd]">{leverage}x</span></div><div className="mt-5 h-20 rounded-xl bg-[linear-gradient(180deg,rgba(196,181,253,.15),transparent)]"><svg viewBox="0 0 520 100" preserveAspectRatio="none" className="h-full w-full" aria-hidden="true"><path d="M0 80 C45 74 53 54 92 66 S140 74 172 48 S215 61 245 35 S292 50 320 28 S367 37 402 17 S452 29 520 8" fill="none" stroke="#c4b5fd" strokeWidth="3" /></svg></div><div className="mt-4 flex justify-between font-mono text-[9px] uppercase tracking-wider text-[#887078]"><span>Experimental leverage</span><span className="text-[#c4b5fd]">{leverage}x</span></div><input aria-label="Experimental leverage preview" type="range" min="1" max="50" value={leverage} onChange={(event) => setLeverage(Number(event.target.value))} className="mt-2 w-full accent-[#c4b5fd]" /></div><p className="mt-4 font-mono text-[10px] leading-5 text-[#887078]">The trading surface is an exploration of what comes next. The live product today is the STRK20 privacy wallet.</p></div>;
