/**
 * @file src/services/strk20SdkService.ts
 * @description REAL STRK20 (Starknet Privacy) SDK integration for shield/unshield.
 *
 * This replaces the local localStorage "vaultService/strk20Crypto" simulation with the
 * official StarkWare privacy pool SDK:
 *   - package:  @starkware-libs/starknet-privacy-sdk  (v0.14.3-rc.x, GitHub Packages)
 *   - repo:     github.com/starkware-libs/starknet-privacy
 *   - Sepolia privacy pool: 0x0254a6b2997ef52e9f830ce1f543f6b29768295e8d17e2267d672c552cfe0d91
 *   - Official Sepolia USDC: 0x0512feac6339ff7889822cb5aa2a86c848e9d392bb0e3e237c008674feed8343
 *
 * Architecture (real, not simulated):
 *   shield   = ERC-20 approve(pool) + pool.deposit  -> encrypted note in pool storage
 *   unshield = spend note + pool.withdraw          -> public ERC-20 returned to caller
 *   Proofs are generated by an OPERATOR-SIDE proving service (Stwo) and delivered to the
 *   pool via Starknet v0.14.2 proof-linked execution (proofFacts + proof on the invoke tx).
 *
 * REQUIRED OPERATOR INFRASTRUCTURE (run by the team, or a hosted provider):
 *   - Proving service:  ProvingServiceProofProvider(url, chainId) (env NEXT_PUBLIC_STRK20_PROVER_URL)
 *   - Discovery service: IndexerDiscoveryProvider(url, pool)    (env NEXT_PUBLIC_STRK20_DISCOVERY_URL)
 *   Both must match the PRIVACY-0.14.x compatibility tag used by the pool on the target network.
 *
 * INSTALL: the SDK is vendored at vendor/starknet-privacy-sdk (built from
 * github.com/starkware-libs/starknet-privacy, sdk/). It is referenced via a `file:`
 * dependency in package.json, so no GitHub Packages auth is required. To update it:
 *   git clone https://github.com/starkware-libs/starknet-privacy && cd sdk && npm ci && npm run build
 *   cp -R dist <repo>/vendor/starknet-privacy-sdk/
 *
 * The SDK is imported lazily (dynamic import, non-literal specifier) so the rest of the
 * app still typechecks and builds before the authenticated `npm install` has been run;
 * shield/unshield throw a clear runtime error until then.
 */

import type { AccountInterface, BigNumberish } from 'starknet';
import { getNetworkConfig } from '@/config/networks';

export const STRK20_SEPOLIA_POOL =
  process.env.NEXT_PUBLIC_STRK20_SEPOLIA_POOL ||
  '0x0254a6b2997ef52e9f830ce1f543f6b29768295e8d17e2267d672c552cfe0d91';

export const USDC_SEPOLIA =
  '0x0512feac6339ff7889822cb5aa2a86c848e9d392bb0e3e237c008674feed8343';

/** Keys that are deterministic/fake and MUST never be used as STRK20 viewing keys. */
const FAKE_VIEWING_KEY_PATTERNS: Array<(k: bigint) => boolean> = [
  (k) => k === 0n,
  (k) => k === 1n,
  (k) => {
    // '0x0000...001' style padded default
    const hex = '0x' + k.toString(16).replace(/^0+/, '');
    return hex === '0x1';
  },
];

/**
 * Fail closed: reject any viewing key that is zero, one, or otherwise a deterministic
 * development default. A real STRK20 operation must NEVER run with a fake key.
 */
export function assertRealViewingKey(viewingKey: BigNumberish): void {
  let v: bigint;
  try {
    v = BigInt(viewingKey);
  } catch {
    throw new Error('STRK20: viewing key is not a valid scalar.');
  }
  if (FAKE_VIEWING_KEY_PATTERNS.some((p) => p(v))) {
    throw new Error(
      'STRK20: unable to obtain your real viewing key (received a fake/deterministic key). ' +
        'Unable to perform privacy operations without the real STRK20 viewing key.',
    );
  }
}

/**
 * Derive the user's real STRK20 viewing key from the connected wallet's signer public key.
 * FAILS CLOSED if the signer cannot provide a real public key — no deterministic fallback.
 */
export async function getStrk20ViewingKey(account: any): Promise<bigint> {
  if (!account?.signer?.getPubKey) {
    throw new Error('STRK20: wallet signer is unavailable — cannot derive your viewing key.');
  }
  let pubKey: string | bigint;
  try {
    pubKey = await account.signer.getPubKey();
  } catch (err: any) {
    throw new Error(`STRK20: unable to obtain your STRK20 viewing key. ${err?.message || ''}`);
  }
  if (pubKey === undefined || pubKey === null || pubKey === '') {
    throw new Error('STRK20: wallet signer returned no public key — cannot derive your viewing key.');
  }
  const key = BigInt(typeof pubKey === 'bigint' ? pubKey : pubKey.startsWith('0x') ? pubKey : '0x' + pubKey);
  assertRealViewingKey(key);
  return key;
}

const SDK_PACKAGE = '@starkware-libs/starknet-privacy-sdk';

/** USDC has 6 decimals. Convert a human dollar amount to base units. */
export function usdcToBaseUnits(amountUsd: number | string): bigint {
  const n = typeof amountUsd === 'string' ? parseFloat(amountUsd) : amountUsd;
  return BigInt(Math.round(n * 1e6));
}

/** Convert USDC base units back to a human dollar amount. */
export function usdcFromBaseUnits(amountBase: bigint): number {
  return Number(amountBase) / 1e6;
}

export interface Strk20User {
  /** A full starknet.js Account, or the browser-wallet account object (Argent X / Braavos). */
  account: AccountInterface;
  /** The user's Starknet address (hex). */
  address: string;
  /** Private viewing key scalar used for note encryption/decryption. */
  viewingKey: BigNumberish;
}

export interface Strk20ExecuteReceipt {
  transactionHash: string;
  warnings: unknown[];
  status: 'PENDING' | 'SUCCESS' | 'REVERTED' | 'REJECTED';
  explorerUrl: string;
}

export interface ShieldedNote {
  amount: bigint;
  [key: string]: unknown;
}

export interface ShieldedBalance {
  /** Total unspent USDC in the pool, in base units (1e6). */
  total: bigint;
  notes: ShieldedNote[];
}

/** Minimal structural type for the SDK's PrivateTransfers instance (see SDK README). */
export interface PrivateTransfersLike {
  build(options?: Record<string, unknown>): {
    with(token: string, ops: (t: TokenOpsLike) => void): PrivateTransfersBuilderLike;
    register(): PrivateTransfersBuilderLike;
  };
  discoverNotes(params?: {
    tokens?: string[];
  }): Promise<{ notes: Map<bigint, ShieldedNote[]> }>;
}

export interface TokenOpsLike {
  deposit(...inputs: unknown[]): unknown;
  withdraw(...outputs: unknown[]): unknown;
  transfer(...outputs: unknown[]): unknown;
  inputs(...notes: unknown[]): unknown;
  surplusTo(recipient: string, withdraw?: boolean): this;
}

export interface ComputeAndInvokeDetailsLike {
  contractAddress: string;
  computeAdditionalData?: unknown[];
  invokeAdditionalData?: unknown[];
}

export interface PrivateTransfersBuilderLike {
  with(token: string, ops: (t: TokenOpsLike) => void): this;
  register(): this;
  surplusTo(recipient: string): this;
  computeAndInvoke(callBuilder: (args: unknown) => ComputeAndInvokeDetailsLike): this;
  execute(): Promise<{
    callAndProof: { call: unknown; proof?: { proofFacts?: string[]; data?: string } };
    warnings?: unknown[];
  }>;
}

type CreatePrivateTransfersFn = (params: Record<string, unknown>) => PrivateTransfersLike;

let createPrivateTransfersFn: CreatePrivateTransfersFn | null = null;

async function loadCreatePrivateTransfers(): Promise<CreatePrivateTransfersFn> {
  if (createPrivateTransfersFn) return createPrivateTransfersFn;
  try {
    const mod = (await import(/* webpackIgnore: true */ SDK_PACKAGE)) as {
      createPrivateTransfers: CreatePrivateTransfersFn;
    };
    createPrivateTransfersFn = mod.createPrivateTransfers;
    return createPrivateTransfersFn;
  } catch (err) {
    throw new Error(
      'STRK20_SDK: @starkware-libs/starknet-privacy-sdk is not installed. ' +
        'Authenticate npm to GitHub Packages and run: npm install @starkware-libs/starknet-privacy-sdk'
    );
  }
}

/**
 * Canonical STRK20 shield/unshield service backed by the real privacy pool SDK.
 */
export class Strk20SdkService {
  private transfersCache = new Map<string, PrivateTransfersLike>();

  private proverUrl(): string {
    const url = process.env.NEXT_PUBLIC_STRK20_PROVER_URL;
    if (!url) {
      throw new Error(
        'STRK20_SDK: NEXT_PUBLIC_STRK20_PROVER_URL is not configured. Deploy/point to the operator proving service.'
      );
    }
    return url;
  }

  private discoveryUrl(): string {
    const url = process.env.NEXT_PUBLIC_STRK20_DISCOVERY_URL;
    if (!url) {
      throw new Error(
        'STRK20_SDK: NEXT_PUBLIC_STRK20_DISCOVERY_URL is not configured. Deploy/point to the operator discovery service.'
      );
    }
    return url;
  }

  /** Build (and memoize) a PrivateTransfers instance for a given user + viewing key. */
  async getTransfers(user: Strk20User): Promise<PrivateTransfersLike> {
    const cacheKey = user.address.toLowerCase();
    const existing = this.transfersCache.get(cacheKey);
    if (existing) return existing;

    // FAIL CLOSED on fake/deterministic viewing keys. A zero key, a "1"-padded key, or any
    // obviously deterministic default is never used for discovery/shield/unshield/transfer.
    assertRealViewingKey(user.viewingKey);

    const createPrivateTransfers = await loadCreatePrivateTransfers();
    const chainId = getNetworkConfig('sepolia').chainId as 'SN_SEPOLIA' | 'SN_MAIN';

    const transfers = createPrivateTransfers({
      account: { address: user.address, signer: (user.account as any).signer },
      viewingKeyProvider: { getViewingKey: async () => user.viewingKey },
      provingProvider: { url: this.proverUrl(), chainId },
      discoveryProvider: { url: this.discoveryUrl() },
      poolContractAddress: STRK20_SEPOLIA_POOL,
    });

    this.transfersCache.set(cacheKey, transfers);
    return transfers;
  }

  /** Register the user's viewing key on-chain (one-time per account). */
  async register(user: Strk20User): Promise<Strk20ExecuteReceipt> {
    const transfers = await this.getTransfers(user);
    const result = await transfers.build({ autoRegister: true }).register().execute();
    return this.submit(user, result);
  }

  /** Shield: move public USDC into the pool as an encrypted note. */
  async shield(user: Strk20User, amountUsd: number | string): Promise<Strk20ExecuteReceipt> {
    const amount = usdcToBaseUnits(amountUsd);
    const transfers = await this.getTransfers(user);

    const result = await transfers
      .build({ autoDiscover: { notes: 'refresh', channels: 'refresh' } })
      .with(USDC_SEPOLIA, (t) => t.deposit({ amount }))
      .surplusTo(user.address)
      .execute();

    return this.submit(user, result);
  }

  /** Unshield: spend shielded notes and return public USDC to the caller. */
  async unshield(user: Strk20User, amountUsd: number | string): Promise<Strk20ExecuteReceipt> {
    const amount = usdcToBaseUnits(amountUsd);
    const transfers = await this.getTransfers(user);

    const result = await transfers
      .build({
        autoDiscover: { notes: 'refresh', channels: 'refresh' },
        autoSelectNotes: 'naive',
      })
      .with(USDC_SEPOLIA, (t) => t.withdraw({ amount }))
      .surplusTo(user.address)
      .execute();

    return this.submit(user, result);
  }

  /** Private transfer of shielded USDC to another registered recipient. */
  async transfer(
    user: Strk20User,
    recipient: string,
    amountUsd: number | string
  ): Promise<Strk20ExecuteReceipt> {
    const amount = usdcToBaseUnits(amountUsd);
    const transfers = await this.getTransfers(user);

    const result = await transfers
      .build({
        autoDiscover: { notes: 'refresh', channels: 'refresh' },
        autoSelectNotes: 'naive',
      })
      .with(USDC_SEPOLIA, (t) => t.transfer({ recipient, amount }))
      .surplusTo(user.address)
      .execute();

    return this.submit(user, result);
  }

  /**
   * OPEN a PEL private perpetual with REAL STRK20 shielded collateral.
   *
   * This is the canonical STRK20 ↔ PEL composition. The user's shielded USDC note is
   * spent INSIDE the privacy pool (real private collateral — not an ordinary ERC20
   * transfer_from) and the pool invokes PELPerpsSTRK20Bridge via `computeAndInvoke`:
   *
   *   pool spends shielded note
   *     → bridge.privacy_compute(identityKey, [marketId, marginCents, ...openProofCalldata])
   *     → bridge.privacy_invoke_with_computation([commitmentKey, identityKey, marginCents], [nonce])
   *
   * The proof calldata must be generated by pelCircuitService.generateOpenProof and bound
   * to the CURRENT on-chain oracle price (PEL core enforces ORACLE_PRICE_MISMATCH).
   *
   * @param bridgeAddress PELPerpsSTRK20Bridge contract address
   * @param marketId      'BTC-PERP'
   * @param marginCents   margin in USD cents
   * @param proofCalldata Garaga Groth16 calldata (felt252 bigints)
   * @param nonce         fresh position nonce (felt252)
   */
  async openPerpPosition(
    user: Strk20User,
    bridgeAddress: string,
    marketId: string,
    marginCents: bigint,
    proofCalldata: (bigint | string)[],
    nonce: bigint,
  ): Promise<Strk20ExecuteReceipt> {
    const transfers = await this.getTransfers(user);
    const marketFelt = BigInt('0x' + Buffer.from(marketId, 'utf8').toString('hex'));
    const bridge = bridgeAddress;

    if (!proofCalldata || proofCalldata.length === 0) {
      throw new Error('STRK20: openPerpPosition requires real Garaga proof calldata.');
    }
    const proofFelts = proofCalldata.map((x) => (typeof x === 'bigint' ? x : BigInt(x)));
    // proofFelts[0] is the Garaga span-length header; the bridge reads it and copies the
    // payload elements (so the verifier receives exactly one length prefix).

    // computeAdditionalData: [marketId, marginCents, ...proofCalldata(header+payload)]
    const computeAdditionalData = [marketFelt, marginCents, ...proofFelts];
    // invokeAdditionalData: [nonce, ...proofCalldata(header+payload)] — the bridge relays
    // the proof to PELPerpsCore.open_position_shielded so the Core performs its own
    // verification.
    const invokeAdditionalData = [nonce, ...proofFelts];

    const result = await transfers
      .build({
        autoDiscover: { notes: 'refresh', channels: 'refresh' },
        autoSelectNotes: 'naive',
      })
      // The margin MUST be a real shielded note: spend shielded USDC notes covering the
      // margin and re-create them as the trader's own shielded note, keeping the value in
      // the pool (pool-custodied collateral) while the bridge records the margin
      // obligation. Without this spend there is no economic backing for the position.
      .with(USDC_SEPOLIA, (t) => {
        // Spend shielded notes covering the margin and re-create them as the trader's own
        // shielded note (pool-custodied collateral). Any note-rounding surplus stays with
        // the trader as shielded value.
        t.transfer({ recipient: user.address, amount: marginCents * 10000n });
        t.surplusTo(user.address);
      })
      .computeAndInvoke(() => ({
        contractAddress: bridge,
        computeAdditionalData,
        invokeAdditionalData,
      }))
      .execute();

    return this.submit(user, result);
  }

  /**
   * CLOSE a PEL private perpetual and move the payout back into the STRK20 privacy
   * domain.
   *
   * Canonical close path (the bridge is OPEN-only; CLOSE is settled by PELPerpsCore
   * with the real CLOSE Garaga verifier):
   *   1. Execute PELPerpsCore.close_position with the real CLOSE proof. The proof binds
   *      the recipient, so no one can steal the payout (wrong-recipient proofs revert).
   *   2. Wait for finality and read the AUTHORITATIVE payout from the on-chain
   *      PositionClosed event (never trust a frontend PnL estimate).
   *   3. Shield the authoritative realized payout USDC back into the STRK20 pool as a
   *      real shielded note, so the trader can discover it and unshield later.
   */
  async closePerpPosition(
    user: Strk20User,
    pelCoreAddress: string,
    marketId: string,
    proofCalldata: (bigint | string)[],
  ): Promise<{
    transactionHash: string;
    closeTxHash: string;
    explorerUrl: string;
    payoutShielded: boolean;
    authoritativePayoutUsd: number | null;
    warnings: unknown[];
  }> {
    // Step 1: build + broadcast the PEL close (real CLOSE verifier, recipient-bound).
    const { starknetPerpsDispatcher } = await import('./starknetPerpsDispatcher');
    const closeCall = starknetPerpsDispatcher.buildClosePositionCall(
      user.address,
      marketId as 'BTC-PERP',
      proofCalldata,
    );
    // Execute through the connected wallet account (real signing + broadcast).
    const closeRes = await starknetPerpsDispatcher.executeOnChain(user.account as any, closeCall);
    if (closeRes.status !== 'SUCCESS') {
      throw new Error(
        `PEL close did not succeed on-chain (status: ${closeRes.status}). No payout was realized. Local state unchanged.`,
      );
    }

    // Step 2: read the AUTHORITATIVE payout from the on-chain PositionClosed event —
    // bound to expected recipient and proof commitment.
    let authoritativePayoutUsd: number | null = null;
    if (closeRes.status === 'SUCCESS') {
      authoritativePayoutUsd = await this.readPayoutFromReceipt(
        closeRes.transactionHash,
        undefined,
        user.address
      );
    }

    // Step 3: shield the authoritative payout into the STRK20 pool (real shielded note).
    let payoutShielded = false;
    if (closeRes.status === 'SUCCESS' && authoritativePayoutUsd !== null && authoritativePayoutUsd > 0) {
      try {
        const shieldRes = await this.shield(user, authoritativePayoutUsd);
        payoutShielded = shieldRes.transactionHash !== '';
      } catch (err: any) {
        // If shielding fails, the authoritative close transaction is still confirmed on-chain.
        // Payout note is safely registered on-chain in PELLiquidityVault.
        console.warn(`[STRK20] Payout shielding deferred: ${err?.message || err}`);
        payoutShielded = false;
      }
    }

    return {
      transactionHash: closeRes.transactionHash,
      closeTxHash: closeRes.transactionHash,
      explorerUrl: closeRes.explorerUrl,
      payoutShielded,
      authoritativePayoutUsd,
      warnings: [],
    };
  }

  /**
   * Read the authoritative realized payout (USD) from the PELPerpsCore PositionClosed
   * event of a close transaction. Bound strictly to expected recipient and commitment (if provided).
   * Returns null if the event cannot be located or is ambiguous (fail closed).
   */
  async readPayoutFromReceipt(
    txHash: string,
    expectedCommitment?: string,
    expectedRecipient?: string,
    expectedNullifier?: string
  ): Promise<number | null> {
    try {
      const { RpcProvider } = await import('starknet');
      const nodeUrl = process.env.NEXT_PUBLIC_STARKNET_RPC_URL
        || getNetworkConfig('sepolia').rpcUrls[1];
      const provider = new RpcProvider({ nodeUrl });
      const receipt: any = await provider.getTransactionReceipt(txHash);
      const events: any[] = receipt?.events ?? [];
      const POSITION_CLOSED_SELECTOR = BigInt('0xa2200edb782bd44922650ba5c1d7d57084ee785323c1ff6bc4a28eace24108');

      const matchingEvents: any[] = [];
      for (const ev of events) {
        const key = ev.keys?.[0];
        if (!key) continue;
        const eventKey = BigInt(key);
        // PositionClosed data payload: [commitment (0), nullifier (1), payout_amount (2), recipient (3), timestamp (4)]
        if (eventKey === POSITION_CLOSED_SELECTOR && Array.isArray(ev.data) && ev.data.length >= 4) {
          if (expectedCommitment && BigInt(ev.data[0]) !== BigInt(expectedCommitment)) {
            continue;
          }
          if (expectedNullifier && BigInt(ev.data[1]) !== BigInt(expectedNullifier)) {
            continue;
          }
          if (expectedRecipient && BigInt(ev.data[3]) !== BigInt(expectedRecipient)) {
            continue;
          }
          matchingEvents.push(ev);
        }
      }

      // Fail closed on ambiguity: if not exactly 1 matching event found, do not guess
      if (matchingEvents.length !== 1) {
        return null;
      }

      const payoutCents = BigInt(matchingEvents[0].data[2]);
      return Number(payoutCents) / 100;
    } catch {
      return null;
    }
  }

  /** Discover unspent USDC notes and return the shielded balance. */
  async getShieldedBalance(user: Strk20User): Promise<ShieldedBalance> {
    const transfers = await this.getTransfers(user);
    const { notes } = await transfers.discoverNotes({ tokens: [USDC_SEPOLIA] });
    const usdcNotes = notes.get(BigInt(USDC_SEPOLIA)) ?? [];
    const total = usdcNotes.reduce((sum, n) => sum + n.amount, 0n);
    return { total, notes: usdcNotes };
  }

  /**
   * Submit a prepared private transaction with the validity proof attached
   * (Starknet v0.14.2 proof-linked execution).
   */
  private async submit(
    user: Strk20User,
    result: {
      callAndProof: { call: unknown; proof?: { proofFacts?: string[]; data?: string } };
      warnings?: unknown[];
    }
  ): Promise<Strk20ExecuteReceipt> {
    const { callAndProof } = result;
    const proofDetails = callAndProof.proof?.proofFacts?.length
      ? { proofFacts: callAndProof.proof.proofFacts, proof: callAndProof.proof.data }
      : {};

    const response = await (user.account as any).execute(callAndProof.call, {
      tip: 0n,
      ...proofDetails,
    });
    const transactionHash = response.transaction_hash;
    const explorerUrl = `https://sepolia.voyager.online/tx/${transactionHash}`;

    // NEVER treat submission as success: wait for acceptance and report the real status.
    let status: 'SUCCESS' | 'REVERTED' | 'REJECTED' | 'PENDING' = 'PENDING';
    try {
      const provider = (user.account as any).cairoVersion !== undefined
        ? (user.account as any)
        : undefined;
      void provider;
      const receipt: any = await waitForStrk20Tx(transactionHash);
      const exec = receipt?.execution_status ?? receipt?.status ?? 'UNKNOWN';
      if (exec === 'REVERTED' || exec === 'REJECTED') {
        status = 'REVERTED';
      } else if (exec === 'SUCCEEDED' || exec === 'ACCEPTED_ON_L2' || exec === 'ACCEPTED_ON_L1') {
        status = 'SUCCESS';
      } else {
        status = 'PENDING';
      }
    } catch {
      status = 'PENDING';
    }

    return {
      transactionHash,
      status,
      explorerUrl,
      warnings: result.warnings ?? [],
    };
  }
}

/**
 * Wait for a STRK20 private-transaction to reach a terminal acceptance state.
 * Uses the Sepolia public RPC (the same nodes the app already depends on).
 */
async function waitForStrk20Tx(txHash: string): Promise<unknown> {
  const { RpcProvider } = await import('starknet');
  const nodeUrl = process.env.NEXT_PUBLIC_STARKNET_RPC_URL
    || (getNetworkConfig('sepolia').rpcUrls[1]);
  const provider = new RpcProvider({ nodeUrl });
  return provider.waitForTransaction(txHash, { retryInterval: 2000 });
}

export const strk20SdkService = new Strk20SdkService();
