/**
 * @file src/services/strk20SdkService.ts
 * @description REAL STRK20 (Starknet Privacy) SDK integration for shield/unshield.
 *
 * This replaces the local localStorage "vaultService/strk20Crypto" simulation with the
 * official StarkWare privacy pool SDK:
 *   - package:  @starkware-libs/starknet-privacy-sdk  (v0.14.3-rc.x, GitHub Packages)
 *   - repo:     github.com/starkware-libs/starknet-privacy
 *   - Sepolia privacy pool: 0x0254a6b2997ef52e9f830ce1f543f6b29768295e8d17e2267d672c552cfe0d91
 *   - Official Sepolia USDC: 0x0512feac6339ff7889822cb5aa2a86c848e9d392bb0e3e237c008674feed8343
 *
 * Architecture (real, not simulated):
 *   shield   = ERC-20 approve(pool) + pool.deposit  -> encrypted note in pool storage
 *   unshield = spend note + pool.withdraw          -> public ERC-20 returned to caller
 *   Proofs are generated by an OPERATOR-SIDE proving service (Stwo) and delivered to the
 *   pool via Starknet v0.14.2 proof-linked execution (proofFacts + proof on the invoke tx).
 *
 * REQUIRED OPERATOR INFRASTRUCTURE (run by the team, or a hosted provider):
 *   - Proving service:  ProvingServiceProofProvider(url, chainId) (env NEXT_PUBLIC_STRK20_PROVER_URL)
 *   - Discovery service: IndexerDiscoveryProvider(url, pool)    (env NEXT_PUBLIC_STRK20_DISCOVERY_URL)
 *   Both must match the PRIVACY-0.14.x compatibility tag used by the pool on the target network.
 *
 * INSTALL: the SDK is vendored at vendor/starknet-privacy-sdk (built from
 * github.com/starkware-libs/starknet-privacy, sdk/). It is referenced via a `file:`
 * dependency in package.json, so no GitHub Packages auth is required. To update it:
 *   git clone https://github.com/starkware-libs/starknet-privacy && cd sdk && npm ci && npm run build
 *   cp -R dist <repo>/vendor/starknet-privacy-sdk/
 *
 * The SDK is imported lazily (dynamic import, non-literal specifier) so the rest of the
 * app still typechecks and builds before the authenticated `npm install` has been run;
 * shield/unshield throw a clear runtime error until then.
 */

import type { AccountInterface, BigNumberish } from 'starknet';
import { getNetworkConfig } from '@/config/networks';

export const STRK20_SEPOLIA_POOL =
  process.env.NEXT_PUBLIC_STRK20_SEPOLIA_POOL ||
  '0x0254a6b2997ef52e9f830ce1f543f6b29768295e8d17e2267d672c552cfe0d91';

export const USDC_SEPOLIA =
  '0x0512feac6339ff7889822cb5aa2a86c848e9d392bb0e3e237c008674feed8343';

const SDK_PACKAGE = '@starkware-libs/starknet-privacy-sdk';

/** USDC has 6 decimals. Convert a human dollar amount to base units. */
export function usdcToBaseUnits(amountUsd: number | string): bigint {
  const n = typeof amountUsd === 'string' ? parseFloat(amountUsd) : amountUsd;
  return BigInt(Math.round(n * 1e6));
}

/** Convert USDC base units back to a human dollar amount. */
export function usdcFromBaseUnits(amountBase: bigint): number {
  return Number(amountBase) / 1e6;
}

export interface Strk20User {
  /** A full starknet.js Account, or the browser-wallet account object (Argent X / Braavos). */
  account: AccountInterface;
  /** The user's Starknet address (hex). */
  address: string;
  /** Private viewing key scalar used for note encryption/decryption. */
  viewingKey: BigNumberish;
}

export interface Strk20ExecuteReceipt {
  transactionHash: string;
  warnings: unknown[];
}

export interface ShieldedNote {
  amount: bigint;
  [key: string]: unknown;
}

export interface ShieldedBalance {
  /** Total unspent USDC in the pool, in base units (1e6). */
  total: bigint;
  notes: ShieldedNote[];
}

/** Minimal structural type for the SDK's PrivateTransfers instance (see SDK README). */
export interface PrivateTransfersLike {
  build(options?: Record<string, unknown>): {
    with(token: string, ops: (t: TokenOpsLike) => void): PrivateTransfersBuilderLike;
    register(): PrivateTransfersBuilderLike;
  };
  discoverNotes(params?: {
    tokens?: string[];
  }): Promise<{ notes: Map<bigint, ShieldedNote[]> }>;
}

export interface TokenOpsLike {
  deposit(...inputs: unknown[]): unknown;
  withdraw(...outputs: unknown[]): unknown;
  transfer(...outputs: unknown[]): unknown;
  inputs(...notes: unknown[]): unknown;
  surplusTo(recipient: string, withdraw?: boolean): this;
}

export interface ComputeAndInvokeDetailsLike {
  contractAddress: string;
  computeAdditionalData?: unknown[];
  invokeAdditionalData?: unknown[];
}

export interface PrivateTransfersBuilderLike {
  with(token: string, ops: (t: TokenOpsLike) => void): this;
  register(): this;
  surplusTo(recipient: string): this;
  computeAndInvoke(callBuilder: (args: unknown) => ComputeAndInvokeDetailsLike): this;
  execute(): Promise<{
    callAndProof: { call: unknown; proof?: { proofFacts?: string[]; data?: string } };
    warnings?: unknown[];
  }>;
}

type CreatePrivateTransfersFn = (params: Record<string, unknown>) => PrivateTransfersLike;

let createPrivateTransfersFn: CreatePrivateTransfersFn | null = null;

async function loadCreatePrivateTransfers(): Promise<CreatePrivateTransfersFn> {
  if (createPrivateTransfersFn) return createPrivateTransfersFn;
  try {
    const mod = (await import(/* webpackIgnore: true */ SDK_PACKAGE)) as {
      createPrivateTransfers: CreatePrivateTransfersFn;
    };
    createPrivateTransfersFn = mod.createPrivateTransfers;
    return createPrivateTransfersFn;
  } catch (err) {
    throw new Error(
      'STRK20_SDK: @starkware-libs/starknet-privacy-sdk is not installed. ' +
        'Authenticate npm to GitHub Packages and run: npm install @starkware-libs/starknet-privacy-sdk'
    );
  }
}

/**
 * Canonical STRK20 shield/unshield service backed by the real privacy pool SDK.
 */
export class Strk20SdkService {
  private transfersCache = new Map<string, PrivateTransfersLike>();

  private proverUrl(): string {
    const url = process.env.NEXT_PUBLIC_STRK20_PROVER_URL;
    if (!url) {
      throw new Error(
        'STRK20_SDK: NEXT_PUBLIC_STRK20_PROVER_URL is not configured. Deploy/point to the operator proving service.'
      );
    }
    return url;
  }

  private discoveryUrl(): string {
    const url = process.env.NEXT_PUBLIC_STRK20_DISCOVERY_URL;
    if (!url) {
      throw new Error(
        'STRK20_SDK: NEXT_PUBLIC_STRK20_DISCOVERY_URL is not configured. Deploy/point to the operator discovery service.'
      );
    }
    return url;
  }

  /** Build (and memoize) a PrivateTransfers instance for a given user + viewing key. */
  async getTransfers(user: Strk20User): Promise<PrivateTransfersLike> {
    const cacheKey = user.address.toLowerCase();
    const existing = this.transfersCache.get(cacheKey);
    if (existing) return existing;

    const createPrivateTransfers = await loadCreatePrivateTransfers();
    const chainId = getNetworkConfig('sepolia').chainId as 'SN_SEPOLIA' | 'SN_MAIN';

    const transfers = createPrivateTransfers({
      account: { address: user.address, signer: (user.account as any).signer },
      viewingKeyProvider: { getViewingKey: async () => user.viewingKey },
      provingProvider: { url: this.proverUrl(), chainId },
      discoveryProvider: { url: this.discoveryUrl() },
      poolContractAddress: STRK20_SEPOLIA_POOL,
    });

    this.transfersCache.set(cacheKey, transfers);
    return transfers;
  }

  /** Register the user's viewing key on-chain (one-time per account). */
  async register(user: Strk20User): Promise<Strk20ExecuteReceipt> {
    const transfers = await this.getTransfers(user);
    const result = await transfers.build({ autoRegister: true }).register().execute();
    return this.submit(user, result);
  }

  /** Shield: move public USDC into the pool as an encrypted note. */
  async shield(user: Strk20User, amountUsd: number | string): Promise<Strk20ExecuteReceipt> {
    const amount = usdcToBaseUnits(amountUsd);
    const transfers = await this.getTransfers(user);

    const result = await transfers
      .build({ autoDiscover: { notes: 'refresh', channels: 'refresh' } })
      .with(USDC_SEPOLIA, (t) => t.deposit({ amount }))
      .surplusTo(user.address)
      .execute();

    return this.submit(user, result);
  }

  /** Unshield: spend shielded notes and return public USDC to the caller. */
  async unshield(user: Strk20User, amountUsd: number | string): Promise<Strk20ExecuteReceipt> {
    const amount = usdcToBaseUnits(amountUsd);
    const transfers = await this.getTransfers(user);

    const result = await transfers
      .build({
        autoDiscover: { notes: 'refresh', channels: 'refresh' },
        autoSelectNotes: 'naive',
      })
      .with(USDC_SEPOLIA, (t) => t.withdraw({ amount }))
      .surplusTo(user.address)
      .execute();

    return this.submit(user, result);
  }

  /** Private transfer of shielded USDC to another registered recipient. */
  async transfer(
    user: Strk20User,
    recipient: string,
    amountUsd: number | string
  ): Promise<Strk20ExecuteReceipt> {
    const amount = usdcToBaseUnits(amountUsd);
    const transfers = await this.getTransfers(user);

    const result = await transfers
      .build({
        autoDiscover: { notes: 'refresh', channels: 'refresh' },
        autoSelectNotes: 'naive',
      })
      .with(USDC_SEPOLIA, (t) => t.transfer({ recipient, amount }))
      .surplusTo(user.address)
      .execute();

    return this.submit(user, result);
  }

  /**
   * OPEN a PEL private perpetual with REAL STRK20 shielded collateral.
   *
   * This is the canonical STRK20 ↔ PEL composition. The user's shielded USDC note is
   * spent INSIDE the privacy pool (real private collateral — not an ordinary ERC20
   * transfer_from) and the pool invokes PELPerpsSTRK20Bridge via `computeAndInvoke`:
   *
   *   pool spends shielded note
   *     → bridge.privacy_compute(identityKey, [marketId, marginCents, ...openProofCalldata])
   *     → bridge.privacy_invoke_with_computation([commitmentKey, identityKey, marginCents], [nonce])
   *
   * The proof calldata must be generated by pelCircuitService.generateOpenProof and bound
   * to the CURRENT on-chain oracle price (PEL core enforces ORACLE_PRICE_MISMATCH).
   *
   * @param bridgeAddress PELPerpsSTRK20Bridge contract address
   * @param marketId      'BTC-PERP'
   * @param marginCents   margin in USD cents
   * @param proofCalldata Garaga Groth16 calldata (felt252 bigints)
   * @param nonce         fresh position nonce (felt252)
   */
  async openPerpPosition(
    user: Strk20User,
    bridgeAddress: string,
    marketId: string,
    marginCents: bigint,
    proofCalldata: (bigint | string)[],
    nonce: bigint,
  ): Promise<Strk20ExecuteReceipt> {
    const transfers = await this.getTransfers(user);
    const marketFelt = BigInt('0x' + Buffer.from(marketId, 'utf8').toString('hex'));
    const bridge = bridgeAddress;

    const computeAdditionalData = [
      marketFelt,
      marginCents,
      ...proofCalldata.map((x) => (typeof x === 'bigint' ? x : BigInt(x))),
    ];
    const invokeAdditionalData = [nonce];

    const result = await transfers
      .build({
        autoDiscover: { notes: 'refresh', channels: 'refresh' },
        autoSelectNotes: 'naive',
      })
      .with(USDC_SEPOLIA, (t) => t.surplusTo(user.address))
      .computeAndInvoke(() => ({
        contractAddress: bridge,
        computeAdditionalData,
        invokeAdditionalData,
      }))
      .execute();

    return this.submit(user, result);
  }

  /**
   * CLOSE a PEL private perpetual and receive the payout back in the STRK20 privacy
   * domain. The close proof is generated by pelCircuitService.generateCloseProof; the
   * resulting payout is emitted as a shielded note commitment (create-note) so the
   * trader can unshield later — the payout never touches public ERC20 custody.
   */
  async closePerpPosition(
    user: Strk20User,
    bridgeAddress: string,
    marketId: string,
    proofCalldata: (bigint | string)[],
    payoutCommitment: bigint,
    payoutAmountCents: bigint,
    nonce: bigint,
  ): Promise<Strk20ExecuteReceipt> {
    const transfers = await this.getTransfers(user);
    const marketFelt = BigInt('0x' + Buffer.from(marketId, 'utf8').toString('hex'));
    const bridge = bridgeAddress;

    const computeAdditionalData = [
      marketFelt,
      payoutAmountCents,
      ...proofCalldata.map((x) => (typeof x === 'bigint' ? x : BigInt(x))),
    ];
    const invokeAdditionalData = [payoutCommitment, nonce];

    const result = await transfers
      .build({
        autoDiscover: { notes: 'refresh', channels: 'refresh' },
      })
      // Re-shield the payout into the trader's own shielded note.
      .with(USDC_SEPOLIA, (t) => t.transfer({ recipient: user.address, amount: payoutAmountCents }))
      .computeAndInvoke(() => ({
        contractAddress: bridge,
        computeAdditionalData,
        invokeAdditionalData,
      }))
      .execute();

    return this.submit(user, result);
  }

  /** Discover unspent USDC notes and return the shielded balance. */
  async getShieldedBalance(user: Strk20User): Promise<ShieldedBalance> {
    const transfers = await this.getTransfers(user);
    const { notes } = await transfers.discoverNotes({ tokens: [USDC_SEPOLIA] });
    const usdcNotes = notes.get(BigInt(USDC_SEPOLIA)) ?? [];
    const total = usdcNotes.reduce((sum, n) => sum + n.amount, 0n);
    return { total, notes: usdcNotes };
  }

  /**
   * Submit a prepared private transaction with the validity proof attached
   * (Starknet v0.14.2 proof-linked execution).
   */
  private async submit(
    user: Strk20User,
    result: {
      callAndProof: { call: unknown; proof?: { proofFacts?: string[]; data?: string } };
      warnings?: unknown[];
    }
  ): Promise<Strk20ExecuteReceipt> {
    const { callAndProof } = result;
    const proofDetails = callAndProof.proof?.proofFacts?.length
      ? { proofFacts: callAndProof.proof.proofFacts, proof: callAndProof.proof.data }
      : {};

    const response = await (user.account as any).execute(callAndProof.call, {
      tip: 0n,
      ...proofDetails,
    });

    return {
      transactionHash: response.transaction_hash,
      warnings: result.warnings ?? [],
    };
  }
}

export const strk20SdkService = new Strk20SdkService();
