import { describe, it, expect } from 'vitest';
import { zkProverService, PositionWitness } from '../src/services/zkProverService';
import { pragmaOracleService } from '../src/services/pragmaOracleService';
import {
  calcPnlCents, calcEquityCents, calcMaintMarginCents,
  isLiquidatable, calcFundingCentsPerInterval,
  usdToCents, tokensToSats,
} from '../src/protocol/fixedPoint';
import { BTC_PERP_CONFIG } from '../src/protocol/types';

describe('PEL Private Perpetuals ZK Prover Subsystem (Whitepaper Section 11)', () => {
  const OWNER_SECRET = '0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d';
  const NONCE        = '0x123456789abcdef0123456789abcdef0';
  const MARKET_ID    = 'BTC-PERP';

  const longWitness: PositionWitness = {
    side: 'LONG',
    sizeTokens: 0.51855,
    entryPrice: 96420.50,
    marginUsd: 5000,
    fundingAccumulator: 0,
    nonce: NONCE,
    ownerAddress: OWNER_SECRET,
  };

  it('Circuit 1 & 2: evaluates ownership and opening invariants under leverage constraints', () => {
    // V2 API: ownership is implicit via ownerSecret in commitment; opening invariants via validateLeverage
    const commitment = zkProverService.computePositionCommitment(
      OWNER_SECRET, MARKET_ID, 'LONG',
      tokensToSats(longWitness.sizeTokens),
      usdToCents(longWitness.entryPrice),
      usdToCents(longWitness.marginUsd),
      0n, NONCE,
    );
    expect(commitment.startsWith('0x')).toBe(true);
    expect(commitment.length).toBeGreaterThan(10);

    // Owner valid if they can produce a commitment (deterministic)
    const c2 = zkProverService.computePositionCommitment(
      OWNER_SECRET, MARKET_ID, 'LONG',
      tokensToSats(longWitness.sizeTokens),
      usdToCents(longWitness.entryPrice),
      usdToCents(longWitness.marginUsd),
      0n, NONCE,
    );
    expect(commitment).toBe(c2); // Deterministic
  });

  it('Circuit 3: evaluates exact signed linear PnL without witness exposure', () => {
    // Long PnL: 1 BTC entry $96,420.50 → mark $100,000
    const longPnl = zkProverService.evaluatePnLCircuit('LONG', 1.0, 96420.50, 100000);
    expect(longPnl).toBeCloseTo(3579.50, 1); // floor precision

    // Short PnL: 1 BTC entry $96,420.50 → mark $90,000
    const shortPnl = zkProverService.evaluatePnLCircuit('SHORT', 1.0, 96420.50, 90000);
    expect(shortPnl).toBeCloseTo(6420.50, 1);
  });

  it('Circuit 4: evaluates cumulative funding payment calculation', () => {
    // 1 BTC at $100,000, 0.0012%/hr funding rate, 1 interval
    const qty      = tokensToSats(1.0);
    const price    = usdToCents(100_000);
    const rate     = 120n; // 0.0012% = 120 bps-hundredths... actually 0.0012 * 10000 = 12
    // rate is in bps: 0.0012% = 0.000012 = 12 / 10^6 ... let's use direct BPS_SCALE
    // fundingRateBpsHr: 120 means 0.0120% = $12/hr on $10k notional — no
    // Actually: 120 in our BPS_SCALE (10000) = 1.2% — that's too high
    // Correct: 0.0012% = 0.12 bps = 12 / 10000 bps → fundingRateBpsHr = 12
    const fundingCents = calcFundingCentsPerInterval(qty, price, 12n, 1n);
    // 1 BTC * $100,000 * 0.12% = $120.00 = 12,000 cents
    expect(Number(fundingCents)).toBe(12000);
  });

  it('Circuit 5: verifies solvency risk invariant (Et > Mmaint)', () => {
    // Margin: $5,000, PnL: +$1,000, Size: 0.5 BTC at $100,000, Maintenance: 2% ($1,000)
    const qty     = tokensToSats(0.5);
    const mark    = usdToCents(100_000);
    const margin  = usdToCents(5_000);
    const entry   = usdToCents(98_000); // entry lower than mark → +$1,000 PnL
    const pnl     = calcPnlCents('LONG', qty, entry, mark);
    const equity  = calcEquityCents(margin, pnl, 0n, 0n);
    const maint   = calcMaintMarginCents(qty, mark, BigInt(BTC_PERP_CONFIG.maintenanceMarginBps));

    expect(equity).toBeGreaterThan(maint); // Solvent
    expect(Number(equity) / 100).toBeCloseTo(6000, 0);
    expect(Number(maint) / 100).toBeCloseTo(1000, 0);
    expect(isLiquidatable(margin, pnl, 0n, 0n, qty, mark, BigInt(BTC_PERP_CONFIG.maintenanceMarginBps))).toBe(false);
  });

  it('Circuit 6: proves zero-knowledge liquidation condition (Et <= Mmaint) without witness leakage', () => {
    // Margin: $5,000, PnL: -$4,500, Size: 0.5 BTC at $100,000, Maintenance: 2% ($1,000)
    const qty    = tokensToSats(0.5);
    const mark   = usdToCents(100_000);
    const margin = usdToCents(5_000);
    const entry  = usdToCents(109_000); // entry higher → -$4,500 PnL
    const pnl    = calcPnlCents('LONG', qty, entry, mark);
    const equity = calcEquityCents(margin, pnl, 0n, 0n);
    const maint  = calcMaintMarginCents(qty, mark, BigInt(BTC_PERP_CONFIG.maintenanceMarginBps));

    expect(isLiquidatable(margin, pnl, 0n, 0n, qty, mark, BigInt(BTC_PERP_CONFIG.maintenanceMarginBps))).toBe(true);
    expect(equity).toBeLessThanOrEqual(maint);

    // The liquidation fact_hash is generated by the prover
    const commitment = zkProverService.computePositionCommitment(OWNER_SECRET, MARKET_ID, 'LONG', qty, entry, margin, 0n, NONCE);
    const validNullifier = '0x0111111111111111111111111111111111111111111111111111111111111111';
    const fact = zkProverService.buildFact('LIQUIDATE', MARKET_ID, commitment, validNullifier, margin, mark);
    expect(fact.factHash.startsWith('0x')).toBe(true);
  });

  it('Full STARK Transition Proof Pipeline (SNIP-36)', () => {
    const proofResult = zkProverService.generateTransitionProof(
      'OPEN', longWitness, MARKET_ID, 96420.50, 5000, 50, 0.02
    );

    expect(proofResult.starkVerifierStatus).toBe('POSEIDON_SNIP36_FACT_VALID');
    expect(proofResult.factHash.startsWith('0x')).toBe(true);
    expect(proofResult.publicInputsHash.startsWith('0x')).toBe(true);
    expect(proofResult.commitment.startsWith('0x')).toBe(true);
    expect(proofResult.nullifier.startsWith('0x')).toBe(true);
  });
});

describe('Pragma Oracle Live Service (Whitepaper Section 9)', () => {
  it('fetches live market feeds with freshness verification', async () => {
    const feed = await pragmaOracleService.getMarketPrice('BTC/USD', 'mainnet');
    expect(feed.priceUsd).toBeGreaterThan(0);
    expect(feed.isFresh).toBe(true);
    expect(feed.numSources).toBeGreaterThan(0);
  });
});
