// PEL Groth16 verifier interface — matches the Garaga-generated contract exactly.
//
// One verifier contract is deployed per circuit; each embeds its own verification key
// and is generated by Garaga 1.1.0:
//
//   garaga gen --system groth16 --vk circuits/build/pel_open_verification_key.json
//
// The generated contract exposes a single endpoint:
//   verify_groth16_proof_bn254(full_proof_with_hints: Span<felt252>)
//     -> Result<Span<u256>, felt252>
//
// On success it returns the proof's public inputs as Span<u256> in the SAME ORDER as the
// Circom `component main { public [...] }` declaration. See src/protocol/canonical.ts for the
// canonical layouts. PELPerpsCore treats this returned Span<u256> as the sole source of truth
// for every transition's economic values.

use starknet::ContractAddress;

#[starknet::interface]
pub trait IGroth16VerifierBN254<TContractState> {
    fn verify_groth16_proof_bn254(
        self: @TContractState, full_proof_with_hints: Span<felt252>,
    ) -> Result<Span<u256>, felt252>;
    fn set_mock_public_inputs(ref self: TContractState, inputs: Span<u256>);
    fn set_should_fail(ref self: TContractState, should_fail: bool);
}

/// Dispatcher used by PELPerpsCore to call the deployed Garaga verifier contracts.
#[derive(Copy, Drop)]
pub struct Groth16VerifierDispatcher {
    pub contract_address: ContractAddress,
}

#[generate_trait]
pub impl Groth16VerifierDispatcherImpl of Groth16VerifierDispatcherTrait {
    fn verify(self: @Groth16VerifierDispatcher, full_proof_with_hints: Span<felt252>) -> Result<Span<u256>, felt252> {
        let verifier = IGroth16VerifierBN254Dispatcher {
            contract_address: (*self).contract_address,
        };
        verifier.verify_groth16_proof_bn254(full_proof_with_hints)
    }
}

#[starknet::contract]
pub mod Groth16MockVerifier {
    use super::IGroth16VerifierBN254;
    use starknet::storage::{
        StoragePointerReadAccess, StoragePointerWriteAccess,
        StorageMapReadAccess, StorageMapWriteAccess, Map
    };

    #[storage]
    struct Storage {
        should_fail: bool,
        input_count: u32,
        mock_inputs: Map<u32, u256>,
    }

    #[constructor]
    fn constructor(ref self: ContractState) {
        self.should_fail.write(false);
        self.input_count.write(0);
    }

    #[abi(embed_v0)]
    impl Groth16MockVerifierImpl of IGroth16VerifierBN254<ContractState> {
        fn set_mock_public_inputs(ref self: ContractState, inputs: Span<u256>) {
            let len: u32 = inputs.len();
            self.input_count.write(len);
            let mut i: u32 = 0;
            while i < len {
                self.mock_inputs.write(i, *inputs.at(i));
                i += 1;
            };
        }

        fn set_should_fail(ref self: ContractState, should_fail: bool) {
            self.should_fail.write(should_fail);
        }

        fn verify_groth16_proof_bn254(
            self: @ContractState, full_proof_with_hints: Span<felt252>,
        ) -> Result<Span<u256>, felt252> {
            if self.should_fail.read() {
                return Result::Err('MOCK_VERIFIER_FORCED_FAIL');
            }
            if full_proof_with_hints.len() == 0 {
                return Result::Err('EMPTY_PROOF_CALLDATA');
            }
            if *full_proof_with_hints.at(0) == 0xdead || *full_proof_with_hints.at(0) == 0xbeef {
                return Result::Err('INVALID_GROTH16_PROOF');
            }

            let count = self.input_count.read();
            if count > 0 {
                let mut result: Array<u256> = ArrayTrait::new();
                let mut i: u32 = 0;
                while i < count {
                    result.append(self.mock_inputs.read(i));
                    i += 1;
                };
                return Result::Ok(result.span());
            }

            // Default fallback: parse from calldata if encoded as [num_u256, low0, high0, low1, high1...]
            let num_inputs_felt = *full_proof_with_hints.at(0);
            let num_inputs: u32 = num_inputs_felt.try_into().unwrap_or(0);
            if num_inputs > 0 && full_proof_with_hints.len() >= 1 + (num_inputs * 2) {
                let mut result: Array<u256> = ArrayTrait::new();
                let mut i: u32 = 0;
                while i < num_inputs {
                    let low_felt = *full_proof_with_hints.at(1 + (i * 2));
                    let high_felt = *full_proof_with_hints.at(1 + (i * 2) + 1);
                    let low: u128 = low_felt.try_into().unwrap_or(0);
                    let high: u128 = high_felt.try_into().unwrap_or(0);
                    result.append(u256 { low, high });
                    i += 1;
                };
                return Result::Ok(result.span());
            }

            Result::Ok(ArrayTrait::new().span())
        }
    }
}
